# SPDX-FileCopyrightText: Open Energy Transition gGmbH
# SPDX-License-Identifier: CC0-1.0

exclude: ^(LICENSES)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=2000']

# Sort package imports alphabetically
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

# Python linting and formatting with Ruff (replaces flake8, black, etc.)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.1
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

# Find common spelling mistakes in comments and docstrings
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ['--ignore-regex="\b[A-Z]+\b"', '--ignore-words-list=fom,appartment,bage,ore,setis,tabacco,berfore,vor,fo,FO']
    types_or: [python, rst, markdown]
    files: ^(scripts|doc|src)/

# Do YAML formatting (before the linter checks it)
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    exclude: pinned\.yaml$
    args: [--autofix, --indent, '2', --preserve-quotes]

# Use yamllint to check for valid YAML files and syntax errors
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.36.2
  hooks:
  - id: yamllint
    exclude: pinned\.yaml$
    args: [--format, parsable, -c=.yamllint]

# Format Snakemake rule / workflow files
- repo: https://github.com/snakemake/snakefmt
  rev: v0.10.2
  hooks:
  - id: snakefmt

# Check for FSFE REUSE compliance (licensing) - COMMENTED OUT FOR NOW
# - repo: https://github.com/fsfe/reuse-tool
#   rev: v5.0.2
#   hooks:
#   - id: reuse